spring:
  # ===============================
  # ORACLE DATABASE CONFIGURATION
  # ===============================
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: HOSPITAL_USER
    password: hospital
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/hospitaldb

server:
  port: 8080
