spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver

  data:
    mongodb:
      uri: mongodb://localhost:27017/hospitaldb

server:
  port: 8080